pr: none
trigger: none

variables:
- group: ml-var

stages:
- stage: 'Dev'
  displayName: 'Dev'
  jobs:
  - job: "Provision_Dev"
    displayName: "Provision Dev resources"
    pool:
      name: 'Azure Pipelines'
    timeoutInMinutes: 0
    steps:
    - script: |
        echo "Deploying with:"
        echo "Resource Group: $(RESOURCE_GROUP)"
        echo "Location: $(LOCATION)"
        echo "Base Name: $(BASE_NAME)"
        echo "Workspace: $(WORKSPACE_NAME)"
      displayName: 'Print debug vars'
    
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(RESOURCE_GROUP)'
        location: $(LOCATION)
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/environment_setup/cloud-environment.json'
        overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION) -workspace $(WORKSPACE_NAME)'
        deploymentMode: 'Incremental'
      displayName: 'Deploy OH resources to Azure'
